name: Build and Deploy to Google Cloud Run

on:
  [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo
        env:
          DEBUG_PASSWORD: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          DEBUG_SERVICE: ${{ secrets.SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |- 
          echo $DEBUG_PASSWORD | sed 's/./& /g'
          echo $DEBUG_SERVICE | sed 's/./& /g'
          echo $PROJECT_ID | sed 's/./& /g'
