name: Build and Publish image to DockerHub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into DockerHub
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.REPOSITORY_NAME }}:${{ secrets.DOCKER_TAG }} --push ./backend

      - name: Push Docker Image
        run: docker push ${{ secrets.REPOSITORY_NAME }}:${{ secrets.DOCKER_TAG }}
